name: dependency-check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      # - name: Set up python
      #   id: setup-python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: 3.11
      #----------------------------------------------
      #  -----  install & configure UV  -----
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # Install a specific version of uv.
          version: "0.5.9"
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      # - name: Load cached venv
      #   id: cached-poetry-dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: .venv
      #     key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      # - name: Install dependencies
      #   if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      #   run: poetry install --no-interaction --no-root
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      # - name: Install library
      #   run: poetry install --no-interaction
      #----------------------------------------------
      # run test suite
      #----------------------------------------------
      - name: Run tests
        run: uv run pytest tests/ --cov=./
