name: dependency-check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      #----------------------------------------------
      #  -----  install & configure UV  -----
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # Install a specific version of uv.
          version: "0.5.9"
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      #----------------------------------------------
      # run test suite
      #----------------------------------------------
      - name: Run tests
        run: uv run pytest tests/ --cov=./
