name: Python Tests

on: [pull_request]

#  future update use the better version of the python action
# that uses poetry to manage dependencies
# https://github.com/nickmoreton/wagtail-devtools-cli/blob/main/.github/workflows/test.yaml

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt

    - name: Run pytest
      run: |
        # Run all tests except the ones that are marked as --deselect
        # This is because they can only be run locally till I find a way around that
        pytest --deselect tests/test_main --deselect tests/test_repository
